/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerscienceia;

import java.io.*;
import java.time.Clock;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 * @author Suyashhaspowers
 */

public class FirstForm extends javax.swing.JFrame {

    public int num = 0; //counter for number of clients and pension
    
    public int numpension = 0;
    
    private FirstForm first;
    
    private SecondForm second = new SecondForm();
    
    private ThirdForm third = new ThirdForm();
    
    private FourthForm fourth = new FourthForm();
    
    private FifthForm fifth = new FifthForm();
    
    private SixthForm sixth = new SixthForm();
    
    private LoginForm login = new LoginForm();
   
    // Array of client objects
    public Client [] clients = new Client[20];
    
    //Array of pension objects
    public Pension [] pension = new Pension[20];
   
    // Files for Serialization and File IO
    private File data = new File("c:\\temp\\data.txt\\");
    
    private File clientsData = new File("c:\\temp\\clientdata.ser\\");
    
    private File pensionData = new File("c:\\temp\\pensiondata.ser\\");
    
    private boolean emptyData;
    
    public FirstForm() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        ExitButton = new javax.swing.JButton();
        EnterNewClientButton = new javax.swing.JButton();
        EditClientDetailsButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ViewClientsPensionButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(43, 43, 58));

        ExitButton.setBackground(new java.awt.Color(229, 87, 91));
        ExitButton.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        ExitButton.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        EnterNewClientButton.setBackground(new java.awt.Color(229, 87, 91));
        EnterNewClientButton.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        EnterNewClientButton.setForeground(new java.awt.Color(255, 255, 255));
        EnterNewClientButton.setText("Enter New Client");
        EnterNewClientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnterNewClientButtonActionPerformed(evt);
            }
        });

        EditClientDetailsButton.setBackground(new java.awt.Color(229, 87, 91));
        EditClientDetailsButton.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        EditClientDetailsButton.setForeground(new java.awt.Color(255, 255, 255));
        EditClientDetailsButton.setText("Edit Client Details");
        EditClientDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditClientDetailsButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Lt", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Main Menu");

        ViewClientsPensionButton.setBackground(new java.awt.Color(229, 87, 91));
        ViewClientsPensionButton.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        ViewClientsPensionButton.setForeground(new java.awt.Color(255, 255, 255));
        ViewClientsPensionButton.setText("View Clients and Pension");
        ViewClientsPensionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewClientsPensionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EnterNewClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ViewClientsPensionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EditClientDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(110, 110, 110))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel2)
                    .addContainerGap(362, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(55, 55, 55)
                .addComponent(EnterNewClientButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(ViewClientsPensionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(EditClientDetailsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(504, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(47, 47, 47)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //add Client from second form
    public void addClient(Client c) {
        clients[num] = c;
        emptyData = true;
    }
    
    //add Pension from third form
    public void addPension(Pension a) {
        pension[num] = a;
        num++;
    }
    
    // Send required data from first form to third form
    public void pensionPage() {
        third.calculatePension(this);
        third.setPension(pension);
        third.setNum(num);
        third.setVisible(true);
    }
    
    // Send required data from first form to Sixth Form
    public void viewPensionClient(int clientnum) {
        sixth.getClientNum(clientnum);
        sixth.setClientsAndPension(clients,pension);
        sixth.viewClientsPension(this);
        sixth.getValues();
        sixth.calculatePensionAndSavings();
        sixth.setInitialValues();
        sixth.setVisible(true);
    }
    
    // Read Data at program start
    public void readData() throws ClassNotFoundException {
        
        try {
            //Creates file for txt file for num variable
            if (data.createNewFile()) {
                FileWriter assignZeroValue = new FileWriter(data);
                BufferedWriter bufferedWriter = new BufferedWriter(assignZeroValue);
                bufferedWriter.write("0");
                bufferedWriter.close();
                emptyData = false;
            }
            else {
                //If file already exists for num variable
                System.out.println("File Already Exists");
                emptyData = true;
            }
        } catch (IOException ex) {
            Logger.getLogger(FirstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            //obtain value for number of Clients from previous usage
            FileReader fileReader = new FileReader(data);
            BufferedReader br = new BufferedReader(fileReader);
            num = Integer.parseInt(br.readLine());
            br.close();
        } catch (IOException ex) {
            Logger.getLogger(FirstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (emptyData == true){
            try {
                    // read clients data
                    FileInputStream fis = new FileInputStream(clientsData);
                    ObjectInputStream ois = new ObjectInputStream(fis);
                    clients = (Client[]) ois.readObject();
                    ois.close();
                        
                    //read pension data
                    FileInputStream fisPension = new FileInputStream(pensionData);
                    ObjectInputStream oisPension = new ObjectInputStream(fisPension);
                    pension = (Pension[]) oisPension.readObject();
                    oisPension.close();

                } catch (IOException ex) {
                    Logger.getLogger(FirstForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //set first form visible
        this.setVisible(true);
    }
    
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
      
        try {
            //Write Client Objects to clientData.ser
            FileOutputStream fos = new FileOutputStream(clientsData);
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(clients);
            oos.close();
            
           //Write Pension Objects to pensionData.ser 
           FileOutputStream fosPension = new FileOutputStream(pensionData);
           ObjectOutputStream oosPension = new ObjectOutputStream(fosPension);
           oosPension.writeObject(pension);
           oosPension.close();
           
           //Write num variable to data.txt
           FileWriter fileWriter = new FileWriter(data);
           BufferedWriter bw = new BufferedWriter(fileWriter);
           String numberClients = Integer.toString(num);
           bw.write(numberClients);
           bw.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FirstForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FirstForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void EnterNewClientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnterNewClientButtonActionPerformed
        second.createClient(this);
        this.setVisible(false);
    }//GEN-LAST:event_EnterNewClientButtonActionPerformed

    private void EditClientDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditClientDetailsButtonActionPerformed
        fourth.editClients(this);
        fourth.setClientsAndPension(clients,pension);
        fourth.setNum(num,emptyData);
        fourth.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditClientDetailsButtonActionPerformed

    private void ViewClientsPensionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewClientsPensionButtonActionPerformed
        fifth.getClients(clients);
        fifth.getNum(num,emptyData);
        fifth.viewClients(this);
        fifth.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ViewClientsPensionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException {
                
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditClientDetailsButton;
    private javax.swing.JButton EnterNewClientButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JButton ViewClientsPensionButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setText(int x) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
