/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package computerscienceia;


import java.util.List;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.*;
/**
 *
 * @author Suyashhaspowers
 */
public class FourthForm extends javax.swing.JFrame {

    /**
     * Creates new form FourthForm
     */
    
    // Instance Variables
    private FirstForm first; //First Form Object
    
    private int num; // Counter for number of clients / pensions
    
    private Client clients[]; // Array of clients
    
    private Pension pension[]; // Array of pensions
    
    private int clientnumber; // Each client has a client number
    
    private boolean emptyData; // Determines if there is data in the system
       
    private boolean contribution; // Determins if there is contribution plan
    
    public FourthForm() {
        initComponents();
    }
    public void setClientsAndPension(Client clientArray[],Pension pensionArray[]){
        clients = clientArray;
        pension = pensionArray;
    }
    
    public void setNum(int numValue, boolean empty){
        num = numValue;
        emptyData = empty;
    }
    
    public void editClients(FirstForm f) {
        first = f;
        //Set all text values empty
        NamejTextField1.setText("");
        AgejTextField1.setText("");
        CanadaYearsjTextField4.setText("");
        RetirementAgejTextField3.setText("");
        emailAddress.setText("");
        ExpectedRetirementIncome.setText("");
        IncomeText.setText("");
        YearsSalary.setText("");
        DefinedCB.setText("");
        IncomeText.setText("");
        YesC.setSelected(false);
        CurrentSavings.setText("");
        ClientNumber.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        UpdateListButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ClientNumber = new javax.swing.JTextField();
        SelectButton = new javax.swing.JButton();
        NamejTextField1 = new javax.swing.JTextField();
        AgejTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RetirementAgejTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        CanadaYearsjTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        ReturnButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        DefinedCB = new javax.swing.JTextField();
        YesC = new javax.swing.JCheckBox();
        YearsSalary = new javax.swing.JTextField();
        IncomeText = new javax.swing.JTextField();
        CurrentSavings = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ExpectedRetirementIncome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(42, 42, 56));

        jLabel1.setFont(new java.awt.Font("Roboto Lt", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select Client:");

        jScrollPane1.setViewportView(jList1);

        UpdateListButton.setBackground(new java.awt.Color(226, 86, 90));
        UpdateListButton.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        UpdateListButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateListButton.setText("Update List");
        UpdateListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateListButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter Client Number");

        ClientNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientNumberActionPerformed(evt);
            }
        });

        SelectButton.setBackground(new java.awt.Color(224, 85, 89));
        SelectButton.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        SelectButton.setForeground(new java.awt.Color(255, 255, 255));
        SelectButton.setText("Select");
        SelectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectButtonActionPerformed(evt);
            }
        });

        NamejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamejTextField1ActionPerformed(evt);
            }
        });

        AgejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgejTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name:");

        jLabel4.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Age:");

        jLabel5.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Desired Retirement Age:");

        RetirementAgejTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RetirementAgejTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Years Living in Canada:");

        CanadaYearsjTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanadaYearsjTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email Address:");

        SubmitButton.setBackground(new java.awt.Color(86, 191, 86));
        SubmitButton.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        ReturnButton.setBackground(new java.awt.Color(255, 153, 153));
        ReturnButton.setFont(new java.awt.Font("Roboto Lt", 0, 12)); // NOI18N
        ReturnButton.setText("Return");
        ReturnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnButtonActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Yearly Salary:");

        jLabel9.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Years Recieving Same Salary:");

        jLabel11.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Defined Company Benefit (Monthly):");

        jLabel12.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Defined Contribution Benefit?:");

        DefinedCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DefinedCBActionPerformed(evt);
            }
        });

        YesC.setForeground(new java.awt.Color(255, 255, 255));
        YesC.setText("Yes");
        YesC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesCActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Current Retirement Savings:");

        jLabel13.setFont(new java.awt.Font("Roboto Lt", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Expected Retirement Income:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(SelectButton)
                                    .addGap(31, 31, 31))
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ClientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(UpdateListButton)
                                .addGap(12, 12, 12)))
                        .addGap(63, 63, 63))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18)
                                    .addComponent(CanadaYearsjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(RetirementAgejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel2))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(NamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AgejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addGap(18, 18, 18)
                                    .addComponent(ExpectedRetirementIncome, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ReturnButton))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jLabel12)
                                .addGap(69, 69, 69)
                                .addComponent(YesC))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CurrentSavings, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(jLabel9))
                                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(jLabel11))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DefinedCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(IncomeText, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(YearsSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(SubmitButton)
                                .addGap(298, 298, 298)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(NamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AgejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(RetirementAgejTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CanadaYearsjTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(IncomeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(YearsSalary, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(DefinedCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(YesC)
                                    .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(CurrentSavings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ExpectedRetirementIncome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SubmitButton)
                            .addComponent(ReturnButton))
                        .addGap(16, 16, 16))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(UpdateListButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ClientNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(SelectButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateListButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateListButtonActionPerformed
    DefaultListModel DL = new DefaultListModel();
        
        String tempStr;
        
//      Creating List/Collection of name

        List<String> name = new ArrayList<String>();
        
        // Assigning values to the collection from array of Clients
        for (int t=0; t <= num-1; t++) {
            String clientName = (clients[t].getName()+" - Client Number: "+t);
            name.add(clientName);
        }
        

        //IF there is more than zero clients
        if (emptyData == true){
            
            //If only one client has been entered into system
            if (num == 0) {
                DL.addElement(clients[0].getName()+" - Client Number: 0");
                jList1.setModel(DL);
            }
            //If more than one client has been entered
            else {
                for (int t = 0; t < num-1; t++) {
                    for (int i= 0; i < num - t -1; i++) {
                        if((name.get(i)).compareTo((name.get(i+1)))<0) {
                            tempStr = name.get(i);
                            name.set(i,name.get(i+1));
                            name.set(i+1, tempStr);
                        }
                    }
                }

                for (int b = 1; b <= num; b++) {
                    //place name on list
                    DL.addElement(name.get((num-b)));
                    jList1.setModel(DL);
                }
            }
 
               
        }
        // If there are no clients
        else {
            String z = "Create a Client in the Main Menu";
            DL.addElement(z);
            jList1.setModel(DL);
        }
    }//GEN-LAST:event_UpdateListButtonActionPerformed

    private void SelectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectButtonActionPerformed
       
        boolean y;

        clientnumber = Integer.parseInt(ClientNumber.getText());

        NamejTextField1.setText(clients[clientnumber].getName());
        AgejTextField1.setText(Integer.toString(clients[clientnumber].getAge()));
        CanadaYearsjTextField4.setText(Integer.toString(clients[clientnumber].getCanadaYears()));
        RetirementAgejTextField3.setText(Integer.toString(clients[clientnumber].getAgeRetirement()));
        emailAddress.setText(clients[clientnumber].getEmail());
        ExpectedRetirementIncome.setText(Integer.toString(clients[clientnumber].getFutureRetirementIncome()));
        
        IncomeText.setText(Integer.toString(pension[clientnumber].getIncome()));
        DefinedCB.setText(Integer.toString(pension[clientnumber].getDefinedCompanyBenefit()));
        YearsSalary.setText(Integer.toString(pension[clientnumber].getYearsOfSalary()));
        CurrentSavings.setText(Integer.toString(pension[clientnumber].getCurrentSavings()));
        
        y = pension[clientnumber].getDefinedContribution();
        
        if (y == true) {
            YesC.setSelected(true);
        }
        else {
            YesC.setSelected(false);
        }
        
    }//GEN-LAST:event_SelectButtonActionPerformed

    private void NamejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamejTextField1ActionPerformed

    private void AgejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgejTextField1ActionPerformed

    private void RetirementAgejTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RetirementAgejTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RetirementAgejTextField3ActionPerformed

    private void CanadaYearsjTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanadaYearsjTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanadaYearsjTextField4ActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        // Get data from each client related text field
        String name = NamejTextField1.getText();
        String email = emailAddress.getText();
        int retirementAge = Integer.parseInt(RetirementAgejTextField3.getText());
        int canadaYears = Integer.parseInt(CanadaYearsjTextField4.getText());
        int age = Integer.parseInt(AgejTextField1.getText());
        int futureIncome = Integer.parseInt(ExpectedRetirementIncome.getText());
        
        //Change client data based on textfield values
        clients[clientnumber].changeName(name);
        clients[clientnumber].changeAge(age);
        clients[clientnumber].changeAgeRetirement(retirementAge);
        clients[clientnumber].changeEmail(email);
        clients[clientnumber].changeCanadaYears(canadaYears);
        clients[clientnumber].changeFutureRetirementIncome(futureIncome);
        
        // get data from each pension related text field
        int income = Integer.parseInt(IncomeText.getText());
        int yearsSalary = Integer.parseInt(YearsSalary.getText());
        int definedCB = Integer.parseInt(DefinedCB.getText());
        int currentSavings = Integer.parseInt(CurrentSavings.getText());
        
        int contributionPrice;

        if (contribution == true) {
            contributionPrice = 300;
        }
        else {
            contributionPrice = 0;
        }
        
        // Change pension data based on textfield values
        pension[clientnumber].changeIncome(income);
        pension[clientnumber].changeYearsofSalary(yearsSalary);
        pension[clientnumber].changeDefinedCompanyBenefit(definedCB);
        pension[clientnumber].changeDefinedContribution(contribution);
        pension[clientnumber].changeCurrentSavings(currentSavings);

        this.setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void ReturnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnButtonActionPerformed
        this.setVisible(false);
        first.setVisible(true);
    }//GEN-LAST:event_ReturnButtonActionPerformed

    private void DefinedCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DefinedCBActionPerformed

    }//GEN-LAST:event_DefinedCBActionPerformed

    private void YesCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesCActionPerformed
        contribution = true;
    }//GEN-LAST:event_YesCActionPerformed

    private void ClientNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientNumberActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FourthForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FourthForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FourthForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FourthForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FourthForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgejTextField1;
    private javax.swing.JTextField CanadaYearsjTextField4;
    private javax.swing.JTextField ClientNumber;
    private javax.swing.JTextField CurrentSavings;
    private javax.swing.JTextField DefinedCB;
    private javax.swing.JTextField ExpectedRetirementIncome;
    private javax.swing.JTextField IncomeText;
    private javax.swing.JTextField NamejTextField1;
    private javax.swing.JTextField RetirementAgejTextField3;
    private javax.swing.JButton ReturnButton;
    private javax.swing.JButton SelectButton;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JButton UpdateListButton;
    private javax.swing.JTextField YearsSalary;
    private javax.swing.JCheckBox YesC;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
